#!/usr/bin/env bash

###############################################################################
# Script name:
#   merge_local_producer_qa.sh
#
# Purpose:
#   Equivalent to the legacy 'merge_analysis_results.sh', but adapted for the 
#   locally produced QA files. It merges all individual AnalysisResults_*.root 
#   files generated by the parallel producer batches into a single file using 
#   ROOT's hadd, then deletes the batch files to save space.
#
#   Input  : <WORK_DIR>/results_producer/AnalysisResults_*.root
#   Output : <WORK_DIR>/AnalysisResults_merged.root
#
#   If hadd fails, the unmerged batch files are safely preserved so you can 
#   inspect them or retry the merge without having to re-run the massive 
#   O2 producer pipeline.
#
# Arguments:
#   $1 : WORK_DIR -- absolute path to the per-wagon working directory
#
# Example:
#   ./merge_local_producer_qa.sh \
#       /home/users/cicerodm/RingPol/LHC25ae_pass2_local/ITSandTPC
#
# Dependencies:
#   hadd -- provided by the ROOT / O2 environment. Make sure the O2
#           environment is loaded before calling this script.
#
###############################################################################

# Stop on first error
set -e

###############################################################################
# Read and validate WORK_DIR
###############################################################################
WORK_DIR="$1"

if [ -z "$WORK_DIR" ]; then
  echo "Usage: $0 <WORK_DIR>"
  exit 1
fi

if [ ! -d "$WORK_DIR" ]; then
  echo "Error: WORK_DIR does not exist: ${WORK_DIR}"
  exit 1
fi

RESULTS_DIR="${WORK_DIR}/results_producer"
OUTPUT_FILE="${WORK_DIR}/AnalysisResults_merged.root"

if [ ! -d "$RESULTS_DIR" ]; then
  echo "Error: Producer results directory not found: ${RESULTS_DIR}"
  exit 1
fi

###############################################################################
# Gather input files
###############################################################################
shopt -s nullglob
# We look for batch-level results specifically in the results_producer folder
INPUT_FILES=("${RESULTS_DIR}"/AnalysisResults_*.root)
shopt -u nullglob

if [ ${#INPUT_FILES[@]} -eq 0 ]; then
  echo "Error: No AnalysisResults_*.root batch files found in: ${RESULTS_DIR}"
  echo "Has the producer run already been merged, or did it fail to produce QA?"
  exit 1
fi

echo "============================================================"
echo "  Merging ${#INPUT_FILES[@]} Local QA Result file(s)"
echo "  Input  : ${RESULTS_DIR}/AnalysisResults_*.root"
echo "  Output : ${OUTPUT_FILE}"
echo "============================================================"

###############################################################################
# Run hadd
#
# hadd arguments:
#   -f : overwrite output file if it already exists
#   -j : use multiple threads to speed up the merge (safe default: 16)
###############################################################################
# Temporarily disable 'set -e' so we can catch the hadd exit code gracefully
set +e
hadd -f -j 16 "$OUTPUT_FILE" "${INPUT_FILES[@]}"
HADD_EXIT=$?
set -e

###############################################################################
# Stage-out: remove batch files only on success
###############################################################################
if [ $HADD_EXIT -eq 0 ]; then
  echo ""
  echo "  [OK] hadd succeeded."
  echo "  Cleaning up unmerged batch files in: ${RESULTS_DIR}"
  rm -f "${INPUT_FILES[@]}"
  
  echo ""
  echo "SUCCESS."
  echo "  Merged output : ${OUTPUT_FILE}"
else
  echo ""
  echo "  [FAIL] hadd exited with code ${HADD_EXIT}."
  echo "  Unmerged batch files preserved for inspection in: ${RESULTS_DIR}"
  exit $HADD_EXIT
fi