#!/bin/bash

# ==============================================================================
# ALICE O2 DERIVED DATA CONSUMER LAUNCHER
# ==============================================================================
# Target Task: o2-analysis-lf-lambdajetpolarizationionsderived
# Purpose:     Process the AO2D_Derived*.root files generated by the main launcher.
# ==============================================================================
# Run as:./runDerivedDataConsumer.sh ./dpl-config-JustTOFBase-FullQA_permissivePt.json ./dpl-config-DerivedConsumer-JustLambda.json

# --- INPUT ARGUMENTS ---
JSON_SUFFIX_CONFIG="$1"     # Used only to get derived data extract the suffix (e.g., dpl-config-JustTOFBase-FullQA_permissivePt.json)
JSON_CONSUMER_CONFIG="$2"   # The ACTUAL configuration for this consumer run

# --- PATH SETUP ---
WORK_DIR=$(pwd)
RESULTS_DIR="${WORK_DIR}/results"
DERIVED_AOD_DIR="${RESULTS_DIR}/derived_aods"

# New paths specific to the consumer
CONSUMER_TEMP="${WORK_DIR}/temp_consumer_stage"
CONSUMER_RESULTS="${WORK_DIR}/results_consumer"
CONSUMER_LOGS="${CONSUMER_RESULTS}/logs"

# --- TUNING KNOBS ---
SHM_SIZE="16000000000"         # 16GB
MEM_RATE_LIMIT="2000000000"    # 2GB/s
THREADS=32                     # Threads for the derived task

# ==============================================================================
# 1. SIGNAL HANDLING
# ==============================================================================
cleanup() {
    if [ -d "$CONSUMER_TEMP" ]; then
        echo "  [Cleanup] Removing consumer staging area..."
        rm -rf "$CONSUMER_TEMP" 2>/dev/null
    fi
}

handle_interrupt() {
    echo ""
    echo "!!! INTERRUPT DETECTED (Ctrl+C) !!!"
    echo "    Stopping current jobs..."
    pkill -P $$ 2>/dev/null
    exit 130
}

trap cleanup EXIT
trap handle_interrupt INT TERM

# ==============================================================================
# 2. INITIALIZATION & DYNAMIC NAMING
# ==============================================================================
if [[ -z "$JSON_SUFFIX_CONFIG" ]] || [[ -z "$JSON_CONSUMER_CONFIG" ]]; then
    echo "Usage: $0 <suffix_config.json> <consumer_config.json>"
    exit 1
fi

JSON_SUFFIX_CONFIG=$(realpath "$JSON_SUFFIX_CONFIG")
JSON_CONSUMER_CONFIG=$(realpath "$JSON_CONSUMER_CONFIG")

if [[ ! -d "$DERIVED_AOD_DIR" ]]; then
    echo "ERROR: Derived AOD directory not found at $DERIVED_AOD_DIR"
    exit 1
fi

# --- DYNAMIC FILENAME LOGIC ---
# 1. Extract Data Suffix (Strips "dpl-config-")
#    Example: "dpl-config-JustTOFBase-FullQA_permissivePt" -> "JustTOFBase-FullQA_permissivePt"
DATA_BASENAME=$(basename "$JSON_SUFFIX_CONFIG" .json)
DATA_SUFFIX="${DATA_BASENAME#dpl-config-}"

# 2. Extract Consumer Suffix (Strips "dpl-config-DerivedConsumer-")
#    Example: "dpl-config-DerivedConsumer-JustLambda" -> "JustLambda"
CONS_BASENAME=$(basename "$JSON_CONSUMER_CONFIG" .json)
CONS_SUFFIX="${CONS_BASENAME#dpl-config-DerivedConsumer-}"

# 3. Create the Final Combined Suffix
FINAL_SUFFIX="${DATA_SUFFIX}-${CONS_SUFFIX}"

echo "========================================================"
echo "  Derived Data Consumer Configuration"
echo "  Data Suffix:     ${DATA_SUFFIX}"
echo "  Consumer Suffix: ${CONS_SUFFIX}"
echo "  Final Suffix:    ${FINAL_SUFFIX}"
echo "========================================================"

# Clean start for consumer
rm -rf "$CONSUMER_TEMP" "$CONSUMER_LOGS"
mkdir -p "$CONSUMER_TEMP"
mkdir -p "$CONSUMER_RESULTS"
mkdir -p "$CONSUMER_LOGS"

# Generate the input list dynamically using the DATA_SUFFIX
# Note: This looks for files named with the leading hyphen as output by the main script
DERIVED_LIST="$CONSUMER_TEMP/derived_inputs.txt"

# Prepend "file:" directly while finding the files so the O2 framework reads it properly
find "$DERIVED_AOD_DIR" -maxdepth 1 -name "AO2D_Derived-${DATA_SUFFIX}_*.root" | sort | awk '{print "file:"$0}' > "$DERIVED_LIST"

TOTAL_FILES=$(wc -l < "$DERIVED_LIST")
if [ "$TOTAL_FILES" -eq 0 ]; then
    echo "ERROR: No derived AOD files found matching 'AO2D_Derived-${DATA_SUFFIX}_*.root'!"
    exit 1
fi

echo "  Found $TOTAL_FILES derived files. Processing all at once..."

# ==============================================================================
# 3. EXECUTE CONSUMER PIPELINE
# ==============================================================================
echo "--------------------------------------------------------"
echo " Processing Derived Data Pipeline"
echo "--------------------------------------------------------"

MAIN_LOG="$CONSUMER_LOGS/consumer_run_${FINAL_SUFFIX}.log"
FINAL_OUTPUT="$CONSUMER_RESULTS/ConsumerResults_${FINAL_SUFFIX}.root"

# Run in the consumer temp directory to keep the workspace clean
cd "$CONSUMER_TEMP" || exit 1

# Execute using the Consumer Config
OPTION="-b --configuration json://$JSON_CONSUMER_CONFIG"

echo "  [O2] Launching consumer pipeline..."

time \
o2-analysis-lf-lambdajetpolarizationionsderived ${OPTION} \
    --pipeline lambdajetpolarizationionsderived:$THREADS \
    --aod-file "@${DERIVED_LIST}" \
    --aod-memory-rate-limit "$MEM_RATE_LIMIT" \
    --shm-segment-size "$SHM_SIZE" \
    > "$MAIN_LOG" 2>&1

EXIT_CODE=$?

# ==============================================================================
# 4. STAGE-OUT & CLEANUP
# ==============================================================================
cd "$WORK_DIR" || exit 1

if [ $EXIT_CODE -eq 0 ]; then
    echo "  [OK] Consumer finished successfully."
    
    if [ -f "$CONSUMER_TEMP/AnalysisResults.root" ]; then
        # Move the single output file directly to the results folder
        mv "$CONSUMER_TEMP/AnalysisResults.root" "$FINAL_OUTPUT"
        
        echo ""
        echo "SUCCESS: Consumer run complete."
        echo "Output: $FINAL_OUTPUT"
        
        # Save the CONSUMER config used for this specific run
        cp "$JSON_CONSUMER_CONFIG" "$CONSUMER_RESULTS/consumer-config_${FINAL_SUFFIX}.json"
    else
        echo "    ERROR: AnalysisResults.root not found in consumer output!"
    fi
else
    echo "  [FAIL] Consumer failed with code $EXIT_CODE"
    echo "  Check log: $MAIN_LOG"
fi